name: PR

on:
  pull_request:
    branches: [main]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  dependency-review:
    uses: ./.github/workflows/dependency-review.yml
  trivy:
    uses: ./.github/workflows/trivy.yml
  semgrep:
    uses: ./.github/workflows/semgrep.yml
