name: Sync Upstream

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  sync:
    if: github.repository != 'krypsis-io/.github'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Sync from upstream
        run: |
          git remote add upstream https://github.com/krypsis-io/.github.git
          git fetch upstream main
          git merge upstream/main --ff-only
          git push origin main
